'use client';
import {contextLabels,fieldLabels,combinedKnowledge} from '../../lib/knowledge.mjs';
export function KnowledgeDetails({knowledge}){
 if(!knowledge)return null;
 const groups=[...new Set(knowledge.fields.map(f=>f.kind))];
 return <section className="knowledge-details"><span className="eyebrow">CONHECIMENTO EXTRAÍDO</span><h3>{contextLabels[knowledge.context]??'Conhecimento'}</h3>{!knowledge.fields.length&&<p className="notice">Extração pendente de revisão.</p>}<div className="keyword-tags">{knowledge.keywords.map((k,i)=><span key={i}>{k.term}</span>)}</div>{groups.map(kind=><section key={kind}><h3>{fieldLabels[kind]??'Informações'} <small> · {knowledge.fields.filter(f=>f.kind===kind).length} itens</small></h3>{knowledge.fields.filter(f=>f.kind===kind).map((f,i)=><article className="knowledge-field" key={i}><small>{[...new Set(f.evidence.map(e=>e.source==='caption'?'Legenda do Instagram':e.source==='transcript'?'Áudio transcrito':'Análise visual'))].join(' · ')}</small><h4>{f.name}</h4><p>{f.value}</p><details><summary>Ver evidências da fonte</summary>{f.evidence.map((e,j)=><blockquote key={j}><small>{e.source==='caption'?'Legenda · sem marca temporal de vídeo':`${e.source==='transcript'?'Áudio transcrito':'Vídeo'} · ${e.start_seconds}s–${e.end_seconds}s`}</small><br/>{e.excerpt}</blockquote>)}</details></article>)}</section>)}{!!knowledge.missing_information.length&&<details><summary>Lacunas registradas na análise original</summary>{knowledge.missing_information.map((s,i)=><p key={i}>{s}</p>)}</details>}</section>;
}
export function KnowledgeBook({videos,onOpen}){
 if(!videos.length)return <div className="empty">Nenhum conhecimento encontrado nesta seleção.</div>;
 return <div className="grid knowledge-book">{videos.map(v=>{const k=combinedKnowledge(v);return <article className="knowledge-card" key={v.id}><small>{contextLabels[k.context]??'Conhecimento'}</small><h4>{v.analysis.title}</h4><div className="keyword-tags">{k.keywords.slice(0,4).map((word,i)=><span key={i}>{word.term}</span>)}{k.keywords.length>4&&<span>+{k.keywords.length-4}</span>}</div>{k.fields.length?<><p className="knowledge-preview"><strong>{k.fields[0].name}: </strong>{k.fields[0].value}</p><small>{k.fields.length} informações com evidência</small></>:<p className="notice">Extração pendente de revisão.</p>}<div className="knowledge-actions"><button className="secondary" onClick={()=>onOpen(v)}>Explorar conhecimento e vídeo</button></div></article>;})}</div>;
}
