'use client';
import {useEffect,useState}from 'react';
import {KnowledgeDetails,KnowledgeBook}from './knowledge-view.jsx';
import {searchKnowledge}from '../../lib/knowledge.mjs';
import VideoPreview from './video-preview.jsx';
import {categoryTree,hierarchyMatches}from '../../lib/category-display.mjs';
const money=value=>Number.isFinite(value)?(value/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Indisponível';
export default function Library(){
 const [videos,setVideos]=useState([]),[cursor,setCursor]=useState(null),[controls,setControls]=useState(null),[financial,setFinancial]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('Biblioteca'),[category,setCategory]=useState('Todos'),[subcategory,setSubcategory]=useState('Todos'),[selected,setSelected]=useState(null),[links,setLinks]=useState(''),[message,setMessage]=useState(''),[knowledgeQuery,setKnowledgeQuery]=useState('');
 async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível carregar.');return data;}
 async function load(next=false){setBusy(true);setError('');try{
  const result=await json('/api/library'+(next&&cursor?'?cursor='+encodeURIComponent(cursor):''));
  setVideos(old=>next?[...new Map([...old,...result.videos].map(v=>[v.id,v])).values()]:result.videos);setCursor(result.next_cursor);
  const outcomes=await Promise.allSettled([json('/api/controls'),json('/api/financial')]);
  if(outcomes[0].status==='fulfilled')setControls(outcomes[0].value.automation);else setError(outcomes[0].reason.message);
  if(outcomes[1].status==='fulfilled')setFinancial(outcomes[1].value);else setError(outcomes[1].reason.message);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function change(changes){setBusy(true);setError('');try{const r=await json('/api/controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set',...changes})});setControls(r.automation);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function register(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await json('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({links})});setLinks('');setMessage(`${r.created} novos links cadastrados; ${r.already_present} já estavam na biblioteca. Nenhum processamento foi iniciado pelo cadastro.`);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const categories=categoryTree(videos);
 const children=categories.find(c=>c.name===category)?.children??[];
 const filtered=videos.filter(v=>(view!=='Precisa de atenção'||v.status==='needs_attention')&&hierarchyMatches(v,category,subcategory));
 return <div className="shell"><aside><div className="brand">MEGA <span>BRAIN</span></div><small>SEU ACERVO DE CONHECIMENTO</small><nav>{['Biblioteca','Categorias','Livro de conhecimento','Precisa de atenção'].map(label=><button key={label} className={view===label?'active':''} onClick={()=>{setView(label);setCategory('Todos');setSubcategory('Todos');}}>{label}</button>)}</nav><p className="environment">Google v0<br/>Ambiente independente</p><form action="/auth/logout" method="post"><button className="secondary">Sair</button></form></aside>
 <main><header><div><span className="eyebrow">BIBLIOTECA PESSOAL</span><h1>Conhecimento que fica.</h1><p>Guarde a fonte. Encontre as ideias. Explore o que merece ser aproveitado.</p></div><button className="secondary" onClick={()=>load()} disabled={busy}>Atualizar</button></header>
 {error&&<p role="alert" className="notice">{error}</p>}
 <section className="stats"><div><b>{videos.length}</b><span>vídeos carregados</span></div><div><b>{videos.filter(v=>v.transcript?.trim()).length}</b><span>transcrições nesta seleção</span></div><div><b>{videos.filter(v=>v.analysis).length}</b><span>análises Google nesta seleção</span></div></section>
 <section className="panel"><span className="eyebrow">CONTROLE DE PROCESSAMENTO</span><h2>Seu ritmo, suas escolhas.</h2><p>Os controles valem para novos trabalhos. Execuções já iniciadas podem terminar.</p>
 <div className="switches">{[['enabled','Fila automática','Buscar e preparar novos vídeos'],['transcription_enabled','Transcrições','Transformar áudio em texto'],['analysis_enabled','Análises','Organizar informações e categorias']].map(([key,label,description])=><button key={key} className="toggle" role="switch" aria-checked={Boolean(controls?.[key])} disabled={!controls||busy} onClick={()=>change({[key]:!controls[key]})}><span><strong>{label}</strong><small>{description}</small></span><i className={controls?.[key]?'on':''}/></button>)}</div>
 <div className="bottom"><div><strong>Vídeos em paralelo</strong><div className="pills">{[1,2,3,4].map(n=><button key={n} aria-pressed={controls?.parallelism===n} disabled={!controls||busy} onClick={()=>change({parallelism:n})}>{n}x</button>)}</div></div><div><strong>Controle financeiro Google</strong><p>{money(financial?.spent_cents)} estimados · {money(financial?.reserved_cents)} reservados</p><small>{financial?.paused!==false?'Novas operações pagas permanecem pausadas.':'Processamento sujeito às reservas financeiras.'} {financial?.coverage_verified!==true?'Cobertura dos créditos ainda não confirmada.':''}</small></div></div></section>
 <section><h2>{view}</h2><p>Contagens e categorias consideram os vídeos carregados. Carregue mais para ampliar a seleção.</p>
 {view==='Livro de conhecimento'&&<div className="book-search"><label htmlFor="knowledge-search">Buscar no conhecimento</label><input id="knowledge-search" type="search" value={knowledgeQuery} onChange={e=>setKnowledgeQuery(e.target.value)} placeholder="Receitas com frango, ferramentas de design..."/><p>Informações extraídas das fontes; alegações não são fatos verificados.</p></div>}
 {view!=='Livro de conhecimento'&&<form className="panel link-entry" onSubmit={register}><label htmlFor="reel-links">Adicionar Reels à biblioteca Google</label><p>Cole até 100 links, um por linha. Links existentes são preservados.</p><textarea id="reel-links" value={links} onChange={event=>setLinks(event.target.value)} maxLength={16000} placeholder="https://www.instagram.com/reel/..."/><button disabled={busy||!links.trim()}>Cadastrar links</button>{message&&<p role="status">{message}</p>}</form>}
 {view==='Categorias'&&<div className="category-navigation"><div className="categories"><button className={category==='Todos'?'active':'secondary'} onClick={()=>{setCategory('Todos');setSubcategory('Todos');}}>Todos os temas</button>{categories.map(c=><button className={category===c.name?'active':'secondary'} aria-pressed={category===c.name} key={c.name} onClick={()=>{setCategory(c.name);setSubcategory('Todos');}}><strong>{c.name}</strong><small>{c.count} {c.count===1?'vídeo':'vídeos'}</small></button>)}</div>{category!=='Todos'&&<div className="subcategories"><p>{category} <span> / {subcategory==='Todos'?'Todas as subcategorias':subcategory}</span></p><div className="categories"><button className={subcategory==='Todos'?'active':'secondary'} onClick={()=>setSubcategory('Todos')}>Ver tudo</button>{children.map(c=><button key={c.name} className={subcategory===c.name?'active':'secondary'} aria-pressed={subcategory===c.name} onClick={()=>setSubcategory(c.name)}>{c.name} <small>{c.count}</small></button>)}</div></div>}</div>}
 {view==='Livro de conhecimento'&&<KnowledgeBook videos={filtered.filter(v=>searchKnowledge(v,knowledgeQuery))} onOpen={setSelected}/>}
 {view!=='Livro de conhecimento'&&!filtered.length&&!busy&&<p className="empty">Nenhum vídeo nesta seleção. O acervo da versão antiga permanece preservado na Cloudflare.</p>}
 {view!=='Livro de conhecimento'&&<div className="grid">{filtered.map(v=><article className="card" key={v.id}><VideoPreview id={v.id}/><button className="card-content" onClick={()=>setSelected(v)}><small>{v.status}</small><h3>{v.analysis?.title||v.id}</h3><p>{v.analysis?.summary||'Aguardando análise Google.'}</p><small>{v.duration_seconds?Math.round(v.duration_seconds)+' segundos':'Duração ainda não verificada'}</small></button></article>)}</div>}
 {cursor&&<button className="secondary" disabled={busy} onClick={()=>load(true)}>Carregar mais vídeos</button>}</section>
 {selected&&<dialog open className="detail"><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button><h2>{selected.analysis?.title||selected.id}</h2>{/^https:\/\/(www\.)?instagram\.com\//.test(selected.source_url??'')&&<a href={selected.source_url} target="_blank" rel="noreferrer">Abrir fonte no Instagram ↗</a>}<VideoPreview key={selected.id} id={selected.id} controls/>{selected.error&&<p className="notice">{selected.error}</p>}<h3>Transcrição bruta</h3><p className="transcript">{selected.transcript||(selected.transcript_status==='no_speech_recognized'?'Transcrição concluída: nenhuma fala foi reconhecida. Isso não comprova que o vídeo esteja sem fala.':'Ainda não transcrito.')}</p><KnowledgeDetails knowledge={selected.analysis?.knowledge}/><h3>Informações úteis</h3>{selected.analysis?<><p>{selected.analysis.summary}</p>{selected.analysis.useful_information?.map((item,index)=><section key={index}><h4>{item.claim}</h4><p>{item.application}</p><small>{item.classification}</small>{item.evidence?.map((e,i)=><blockquote key={i}>{e.excerpt} · {e.start_seconds}s–{e.end_seconds}s</blockquote>)}</section>)}<h3>Limitações</h3>{selected.analysis.limitations?.map((text,index)=><p key={index}>{text}</p>)}</>:<p>Aguardando análise Google. Relatórios históricos não contam como nova análise.</p>}</dialog>}
 </main></div>;
}
