'use client';
import {useEffect,useState}from 'react';
import {KnowledgeDetails,KnowledgeBook}from './knowledge-view.jsx';
import {searchKnowledge}from '../../lib/knowledge.mjs';
import VideoPreview from './video-preview.jsx';
import {categoryTree,hierarchyMatches}from '../../lib/category-display.mjs';
import {paginate} from '../../lib/pagination.mjs';
const money=value=>Number.isFinite(value)?(value/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Indisponível';
export default function Library(){
 const [videos,setVideos]=useState([]),[cursor,setCursor]=useState(null),[controls,setControls]=useState(null),[financial,setFinancial]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('Início'),[category,setCategory]=useState('Todos'),[subcategory,setSubcategory]=useState('Todos'),[selected,setSelected]=useState(null),[links,setLinks]=useState(''),[message,setMessage]=useState(''),[knowledgeQuery,setKnowledgeQuery]=useState('');
 async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível carregar.');return data;}
 async function load(next=false){setBusy(true);setError('');try{
  const result=await json('/api/library'+(next&&cursor?'?cursor='+encodeURIComponent(cursor):''));
  setVideos(old=>next?[...new Map([...old,...result.videos].map(v=>[v.id,v])).values()]:result.videos);setCursor(result.next_cursor);
  const outcomes=await Promise.allSettled([json('/api/controls'),json('/api/financial')]);
  if(outcomes[0].status==='fulfilled')setControls(outcomes[0].value.automation);else setError(outcomes[0].reason.message);
  if(outcomes[1].status==='fulfilled')setFinancial(outcomes[1].value);else setError(outcomes[1].reason.message);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function change(changes){setBusy(true);setError('');try{const r=await json('/api/controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set',...changes})});setControls(r.automation);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function register(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await json('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({links})});setLinks('');setMessage(`${r.created} novos links cadastrados; ${r.already_present} já estavam na biblioteca. Nenhum processamento foi iniciado pelo cadastro.`);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(6);
 useEffect(()=>{setPage(1);},[view,category,subcategory,knowledgeQuery,pageSize]);
 const categories=categoryTree(view==='Livro de conhecimento'?videos.filter(v=>v.analysis?.knowledge):videos);
 const children=categories.find(c=>c.name===category)?.children??[];
 const attention=v=>v.status==='needs_attention'||(v.analysis?.knowledge&&v.analysis.knowledge.fields.length===0);
 const filtered=videos.filter(v=>(view!=='Precisa de atenção'||attention(v))&&hierarchyMatches(v,category,subcategory)&&(view!=='Livro de conhecimento'||searchKnowledge(v,knowledgeQuery)));
 const paging=paginate(filtered,page,pageSize);
 const navigate=label=>{setPageSize(label==='Livro de conhecimento'?3:6);setView(label);setCategory('Todos');setSubcategory('Todos');};
 const committed=(financial?.spent_cents??0)+(financial?.reserved_cents??0)+(financial?.ongoing_commitment_cents??0);
 const budget=financial?.pilot_envelope_cents;
 const categoryNav=<div className="category-navigation"><div className="categories"><button className={category==='Todos'?'active':'secondary'} aria-pressed={category==='Todos'} onClick={()=>{setCategory('Todos');setSubcategory('Todos');}}><span className="category-icon" aria-hidden="true">◈</span><strong>Todos os temas</strong><small>{videos.filter(v=>v.analysis).length} fontes analisadas</small></button>{categories.map(c=><button className={category===c.name?'active':'secondary'} aria-pressed={category===c.name} key={c.name} onClick={()=>{setCategory(c.name);setSubcategory('Todos');}}><span className="category-icon" aria-hidden="true">{{'Alimentação':'♧','Tecnologia':'⌘','Saúde e bem-estar':'♡','Trabalho e negócios':'↗','Casa e estilo':'⌂','Viagens e lugares':'◎'}[c.name]||'◇'}</span><strong>{c.name}</strong><small>{c.count} fontes</small></button>)}</div>{category!=='Todos'&&<div className="subcategories categories"><button className={subcategory==='Todos'?'active':'secondary'} onClick={()=>setSubcategory('Todos')}>Todas</button>{children.map(c=><button key={c.name} className={subcategory===c.name?'active':'secondary'} aria-pressed={subcategory===c.name} onClick={()=>setSubcategory(c.name)}>{c.name} <small>{c.count}</small></button>)}</div>}</div>;
 return <div className="shell"><aside><div className="brand">MEGA <span>BRAIN</span></div><small>SEU ACERVO DE CONHECIMENTO</small><nav>{['Início','Biblioteca','Categorias','Livro de conhecimento','Precisa de atenção'].map(label=><button key={label} className={view===label?'active':''} onClick={()=>navigate(label)}>{label}</button>)}</nav><p className="environment">Google v0<br/>Ambiente independente</p><form action="/auth/logout" method="post"><button className="secondary">Sair</button></form></aside>
 <main><header><div><span className="eyebrow">SEU ACERVO DE CONHECIMENTO</span><h1>{view==='Início'?'Visão geral':view}</h1><p>{view==='Início'?'Acompanhe resultados, processamento e orçamento.':view==='Livro de conhecimento'?'Explore temas, palavras-chave e informações com suas fontes.':'Explore seu acervo, uma página por vez.'}</p></div><button className="secondary" onClick={()=>{setPage(1);load();}} disabled={busy}>Atualizar</button></header>
 {error&&<p role="alert" className="notice">{error}</p>}
 {view==='Início'?<>
 <section className="stats dashboard-stats">{[[videos.length,'Vídeos carregados'],[videos.filter(v=>v.transcript?.trim()).length,'Transcrições com texto'],[videos.filter(v=>v.analysis).length,'Análises disponíveis'],[videos.filter(attention).length,'Itens para conferir']].map(([n,label])=><div key={label}><b>{n}</b><span>{label}</span></div>)}</section>
 <div className="dashboard-grid"><section className="panel processing-panel"><div className="panel-heading"><h2>Processamento</h2><span className="status-chip">{controls?.enabled?'Ativado':'Pausado'}</span></div><div className="switches">{[['enabled','Fila automática','Preparar vídeos'],['transcription_enabled','Transcrições','Áudio em texto'],['analysis_enabled','Análises','Extrair conhecimento']].map(([key,label,description])=><button key={key} className="toggle" role="switch" aria-checked={Boolean(controls?.[key])} disabled={!controls||busy} onClick={()=>change({[key]:!controls[key]})}><span><strong>{label}</strong><small>{description}</small></span><i className={controls?.[key]?'on':''}/></button>)}</div><div className="panel-heading"><strong>Vídeos em paralelo</strong><div className="pills">{[1,2,3,4].map(n=><button key={n} aria-pressed={controls?.parallelism===n} disabled={!controls||busy} onClick={()=>change({parallelism:n})}>{n}x</button>)}</div></div><p className="compact-note">Controles valem para novos trabalhos. Itens iniciados podem terminar.</p><small>{financial?.paused!==false?'Novas operações pagas estão pausadas.':'Operações sujeitas às reservas financeiras.'}</small></section>
 <section className="panel budget-panel"><div className="panel-heading"><h2>Orçamento do piloto</h2><strong>{money(budget)}</strong></div><progress aria-label="Orçamento comprometido" max={budget||1} value={Math.min(committed,budget||0)}/><dl className="budget-lines"><div><dt>Gasto estimado</dt><dd>{money(financial?.spent_cents)}</dd></div><div><dt>Reservado</dt><dd>{money(financial?.reserved_cents)}</dd></div><div><dt>Manutenção prevista</dt><dd>{money(financial?.ongoing_commitment_cents)}</dd></div><div className="budget-available"><dt>Disponível no piloto</dt><dd>{money(Number.isFinite(budget)?Math.max(0,budget-committed):undefined)}</dd></div></dl><small>Estimativas internas; não representam a fatura ou o saldo de créditos Google.</small></section>
 <section className="panel"><h2>Falhas e revisões</h2><div className="report-row"><span>Falhas de processamento</span><b>{videos.filter(v=>v.status==='needs_attention').length}</b></div><div className="report-row"><span>Extrações para revisar</span><b>{videos.filter(v=>v.analysis?.knowledge?.fields.length===0).length}</b></div><div className="report-row"><span>Operações com resultado incerto</span><b>{financial?.uncertain_operations??'—'}</b></div><button className="secondary" onClick={()=>navigate('Precisa de atenção')}>Conferir itens</button></section>
 <section className="panel"><h2>Seu livro de conhecimento</h2><div className="report-row"><span>Informações com evidência</span><b>{videos.reduce((n,v)=>n+(v.analysis?.knowledge?.fields.length??0),0)}</b></div><div className="report-row"><span>Palavras-chave extraídas</span><b>{videos.reduce((n,v)=>n+(v.analysis?.knowledge?.keywords.length??0),0)}</b></div><p className="compact-note">Explore o conteúdo por categoria e subcategoria.</p><button onClick={()=>navigate('Livro de conhecimento')}>Abrir livro</button></section></div><p className="scope-note">Indicadores dos {videos.length} vídeos carregados.{cursor?' Há mais itens disponíveis.':''}</p>
 </>:<section>
 {view==='Biblioteca'&&<details className="link-entry"><summary>Adicionar Reels</summary><form className="panel" onSubmit={register}><label htmlFor="reel-links">Até 100 links, um por linha</label><textarea id="reel-links" value={links} onChange={event=>setLinks(event.target.value)} maxLength={16000} placeholder="https://www.instagram.com/reel/..."/><button disabled={busy||!links.trim()}>Cadastrar links</button>{message&&<p role="status">{message}</p>}</form></details>}
 {(view==='Categorias'||view==='Livro de conhecimento')&&categoryNav}
 {view==='Livro de conhecimento'&&<div className="book-search"><label htmlFor="knowledge-search">Buscar no livro</label><input id="knowledge-search" type="search" value={knowledgeQuery} onChange={e=>setKnowledgeQuery(e.target.value)} placeholder="Ingrediente, receita, ferramenta ou conceito..."/></div>}
 <div className="results-heading"><small>{filtered.length} resultados entre {videos.length} vídeos carregados</small><label>Por página <select aria-label="Itens por página" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[3,6,12,24].map(n=><option key={n}>{n}</option>)}</select></label></div>
 {view==='Livro de conhecimento'?<KnowledgeBook videos={paging.items} onOpen={setSelected}/>:<div className="grid">{paging.items.map(v=><article className="card" key={v.id}><VideoPreview id={v.id}/><button className="card-content" onClick={()=>setSelected(v)}><small>{v.status==='needs_attention'?'Precisa de atenção':v.analysis?'Analisado':'Aguardando processamento'}</small><h3>{v.analysis?.title||v.id}</h3><p>{v.analysis?.summary||'Aguardando análise Google.'}</p><small>{v.duration_seconds?Math.round(v.duration_seconds)+' segundos':'Duração ainda não verificada'}</small></button></article>)}</div>}
 {!filtered.length&&!busy&&view!=='Livro de conhecimento'&&<p className="empty">Nenhum item nesta seleção.</p>}
 <div className="pagination" aria-label="Paginação"><button className="secondary" disabled={busy||paging.page<=1} onClick={()=>setPage(paging.page-1)}>Anterior</button><span>Página {paging.page} de {paging.pages}</span><button className="secondary" disabled={busy||paging.page>=paging.pages} onClick={()=>setPage(paging.page+1)}>Próxima</button>{cursor&&<button className="secondary" disabled={busy} onClick={()=>load(true)}>Carregar próximo lote</button>}</div>
 </section>}
 {selected&&<dialog open className="detail"><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button><h2>{selected.analysis?.title||selected.id}</h2>{/^https:\/\/(www\.)?instagram\.com\//.test(selected.source_url??'')&&<a href={selected.source_url} target="_blank" rel="noreferrer">Abrir fonte no Instagram ↗</a>}<VideoPreview key={selected.id} id={selected.id} controls/>{selected.error&&<p className="notice">{selected.error}</p>}<h3>Transcrição bruta</h3><p className="transcript">{selected.transcript||(selected.transcript_status==='no_speech_recognized'?'Transcrição concluída: nenhuma fala foi reconhecida. Isso não comprova que o vídeo esteja sem fala.':'Ainda não transcrito.')}</p><KnowledgeDetails knowledge={selected.analysis?.knowledge}/><h3>Informações úteis</h3>{selected.analysis?<><p>{selected.analysis.summary}</p>{selected.analysis.useful_information?.map((item,index)=><section key={index}><h4>{item.claim}</h4><p>{item.application}</p><small>{item.classification}</small>{item.evidence?.map((e,i)=><blockquote key={i}>{e.excerpt} · {e.start_seconds}s–{e.end_seconds}s</blockquote>)}</section>)}<h3>Limitações</h3>{selected.analysis.limitations?.map((text,index)=><p key={index}>{text}</p>)}</>:<p>Aguardando análise Google. Relatórios históricos não contam como nova análise.</p>}</dialog>}
 </main></div>;
}
