 'use client';
import {useEffect,useRef,useState} from 'react';
import VideoPreview from './video-preview.jsx';
import {combinedKnowledge,reviewIdentity,audioTranscriptLabel,keywordTag,knowledgeSummary} from '../../lib/knowledge.mjs';
const tabs=[['player','Vídeo original'],['knowledge','Conhecimento consolidado'],['keywords','Palavras-chave'],['transcript','Transcrição de áudio'],['caption','Legenda do post'],['visual','Análise do vídeo']];
export default function ReelDetails({video,onClose}){
 const sourceLabel={caption:'Legenda do post',transcript:'Transcrição de áudio',video:'Análise do vídeo'};
 const sourceTab={caption:'caption',transcript:'transcript',video:'visual'};
 const summary=knowledgeSummary(video);
 const [tab,setTab]=useState('knowledge');const closeRef=useRef(null);const report=video.analysis;const knowledge=combinedKnowledge(video);
 useEffect(()=>{const previous=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const key=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus?.();};},[]);
 return <div className="detail-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="reel-detail-title" className="reel-detail" onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=[...e.currentTarget.querySelectorAll('button,a[href],video[controls],input,summary')].filter(n=>!n.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}>
 <header className="detail-heading"><div><small>REEL · {video.id}</small><h2 id="reel-detail-title">{report?.title||video.id}</h2><details className="review-register"><summary>Registro da revisão</summary><small>{reviewIdentity(video)}{!video.analysis?.source_coverage?.caption&&video.knowledge_supplement?.revision_id?' · Complemento: '+video.knowledge_supplement.revision_id:''}</small></details></div><button ref={closeRef} className="detail-close" onClick={onClose} aria-label="Fechar detalhes do Reel">✕ Fechar</button></header>
 <div className="detail-tabs" aria-label="Seções da extração">{tabs.map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':'secondary'} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <div className="detail-scroll"><div className="source-line">{/^https:\/\/(www\.)?instagram\.com\//.test(video.source_url??'')&&<a href={video.source_url} target="_blank" rel="noreferrer">Abrir fonte no Instagram ↗</a>}</div>{video.error&&<p className="notice">{video.error}</p>}
 {tab==='knowledge'&&<section className="curation-summary"><h3>O que vale guardar</h3><p className="summary-lead">{report?.summary||'Ainda não analisado.'}</p>{summary.map(group=><article key={group.kind} className="summary-group"><h4>{group.label}</h4><p>{group.items.slice(0,3).map(item=>`${item.name}: ${item.value}`).join(' · ')}</p>{group.items.length>3&&<details><summary>Mais {group.items.length-3} informações</summary><ul>{group.items.slice(3).map((item,i)=><li key={i}>{item.name}: {item.value}</li>)}</ul></details>}<div className="source-pills">{[...new Set(group.items.flatMap(item=>item.sources))].map(source=><button key={source} onClick={()=>setTab(sourceTab[source]||'knowledge')}>{sourceLabel[source]||source} ↗</button>)}</div></article>)}{!summary.length&&<p>Conhecimento estruturado ainda não disponível.</p>}{!!report?.useful_information?.length&&<details className="summary-group"><summary>Aplicações e evidências</summary>{report.useful_information.map((item,i)=><article key={i}><h4>{item.claim}</h4><p>{item.application}</p><details><summary>Consultar fontes</summary>{item.evidence?.map((e,j)=><blockquote key={j}>{sourceLabel[e.source]}{e.source!=='caption'&&` · ${e.start_seconds}s–${e.end_seconds}s`}<br/>{e.excerpt}</blockquote>)}</details></article>)}</details>}{!!report?.limitations?.length&&<details className="summary-group"><summary>Limitações desta revisão</summary><ul>{report.limitations.map((s,i)=><li key={i}>{s}</li>)}</ul></details>}{video.analysis_candidate&&<details className="summary-group"><summary>Nova revisão aguardando conferência</summary><p>O conhecimento consolidado mantém a revisão anterior.</p><p>{video.analysis_candidate.summary}</p></details>}<small>As informações mantêm suas fontes. Detalhes não informados não são estimados.</small></section>}
 {tab==='keywords'&&<><h3>Palavras-chave</h3><div className="hashtag-list">{knowledge?.keywords.map((k,i)=><span key={i} title={k.term}>{keywordTag(k.term)}</span>)}</div>{!knowledge?.keywords.length&&<p>Ainda não disponíveis.</p>}</>}
 {tab==='transcript'&&<><h3>Transcrição de áudio</h3><p className="transcript">{audioTranscriptLabel(video)}</p></>}
 {tab==='caption'&&<><h3>Legenda publicada no Instagram</h3>{video.source_caption?<><small>Capturada em {video.source_caption.captured_at} · ID {video.source_caption.capture_id}</small><p className="transcript">{video.source_caption.text}</p></>:<p className="notice">Legenda ainda não capturada. Não significa que o post esteja sem descrição.</p>}</>}
 {tab==='player'&&<VideoPreview id={video.id} controls/>}
 {tab==='visual'&&<section className="reading-panel"><h3>O que aparece no vídeo</h3>{report?.visual_observations?.length?<ul>{report.visual_observations.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p>Observações visuais ainda não disponíveis.</p>}<small>Observações da revisão registrada; texto ilegível e detalhes não conferidos permanecem incertos.</small></section>}

 </div></section></div>;
}
