 'use client';
import {useEffect,useRef,useState} from 'react';
import VideoPreview from './video-preview.jsx';
import {KnowledgeDetails} from './knowledge-view.jsx';
import {combinedKnowledge,reviewIdentity} from '../../lib/knowledge.mjs';
const tabs=[['knowledge','Conhecimento consolidado'],['keywords','Palavras-chave'],['transcript','Transcrição de áudio'],['caption','Legenda do post'],['visual','Análise do vídeo'],['combined','Vídeo + texto']];
export default function ReelDetails({video,onClose}){
 const [tab,setTab]=useState('knowledge');const closeRef=useRef(null);const report=video.analysis;const knowledge=combinedKnowledge(video);
 useEffect(()=>{const previous=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const key=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus?.();};},[]);
 return <div className="detail-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="reel-detail-title" className="reel-detail" onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=[...e.currentTarget.querySelectorAll('button,a[href],video[controls],input')].filter(n=>!n.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}>
 <header className="detail-heading"><div><small>REEL · {video.id}</small><h2 id="reel-detail-title">{report?.title||video.id}</h2><small>Revisão: {reviewIdentity(video)}{video.knowledge_supplement?.revision_id?' · Complemento: '+video.knowledge_supplement.revision_id:''}</small></div><button ref={closeRef} className="detail-close" onClick={onClose} aria-label="Fechar detalhes do Reel">✕ Fechar</button></header>
 <div className="detail-tabs" aria-label="Seções da extração">{tabs.map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':'secondary'} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <div className="detail-scroll"><div className="source-line">{/^https:\/\/(www\.)?instagram\.com\//.test(video.source_url??'')&&<a href={video.source_url} target="_blank" rel="noreferrer">Abrir fonte no Instagram ↗</a>}<small>As fontes são separadas; quantidades ausentes não são estimadas.</small></div>{video.error&&<p className="notice">{video.error}</p>}
 {tab==='knowledge'&&<><p className="section-intro">Informações organizadas com origem e evidência. O complemento da legenda foi conferido separadamente; não substitui a análise visual anterior.</p><KnowledgeDetails knowledge={knowledge}/></>}
 {tab==='keywords'&&<><h3>Palavras-chave e suas fontes</h3>{knowledge?.keywords.map((k,i)=><article className="extraction-item" key={i}><h4>{k.term}</h4>{k.evidence.map((e,j)=><small key={j}>{e.source==='caption'?'Legenda do Instagram':e.source==='transcript'?'Transcrição de áudio':'Vídeo'} · {e.excerpt}<br/></small>)}</article>)}</>}
 {tab==='transcript'&&<><h3>Transcrição bruta do áudio</h3><p className="section-intro">STT do Google. Texto da legenda e texto visível no vídeo não fazem parte desta transcrição.</p><p className="transcript">{video.transcript||'Nenhuma fala reconhecida.'}</p><h4>Qualidade informada na análise</h4><p>{report?.transcript_quality?.assessment||'Ainda não avaliada.'}</p></>}
 {tab==='caption'&&<><h3>Legenda publicada no Instagram</h3>{video.source_caption?<><small>Capturada em {video.source_caption.captured_at} · ID {video.source_caption.capture_id}</small><p className="transcript">{video.source_caption.text}</p></>:<p className="notice">Legenda ainda não capturada. Não significa que o post esteja sem descrição.</p>}</>}
 {tab==='visual'&&<><h3>Vídeo e observações visuais</h3><VideoPreview id={video.id} controls/>{report?.visual_observations?.map((s,i)=><article className="extraction-item" key={i}><p>{s}</p></article>)}<p className="section-intro">Observações do relatório existente. Uma referência à duração inteira não comprova conferência quadro a quadro.</p></>}
 {tab==='combined'&&<><h3>Análise integrada existente</h3><p>{report?.summary||'Ainda não analisado.'}</p>{report?.useful_information?.map((item,i)=><article className="extraction-item" key={i}><h4>{item.claim}</h4><p>{item.application}</p>{item.evidence?.map((e,j)=><blockquote key={j}>{e.source==='transcript'?'Áudio transcrito':'Vídeo'} · {e.start_seconds}s–{e.end_seconds}s<br/>{e.excerpt}</blockquote>)}</article>)}<h3>Limitações e lacunas</h3>{report?.limitations?.map((s,i)=><p key={i}>{s}</p>)}{!video.source_caption&&<p className="notice">A legenda do post não foi incluída nesta revisão.</p>}</>}
 </div></section></div>;
}
