import {readFile} from 'node:fs/promises';
import {isAbsolute} from 'node:path';
import {workerRuntime} from '../lib/worker-runtime.mjs';
import {workerHTTP} from '../lib/worker-http.mjs';
const configPath=process.env.MEGABRAIN_V0_WORKER_CONFIG;
if(!configPath||!isAbsolute(configPath))throw new Error('Arquivo absoluto de configuração própria obrigatório.');
const config=JSON.parse(await readFile(configPath,'utf8'));
const preset=JSON.parse(await readFile(new URL('../config/analysis-preset.json',import.meta.url),'utf8'));
const port=Number(process.env.PORT??8080);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('Porta inválida.');
const server=workerHTTP(workerRuntime(config,preset,{withHandler:true}));
server.requestTimeout=30000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
server.listen(port,'0.0.0.0');
for(const signal of ['SIGTERM','SIGINT'])process.once(signal,()=>server.close());
